name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_SHEETDB_CASH_URL: ${{ vars.REACT_APP_SHEETDB_CASH_URL }}
      REACT_APP_SHEETDB_EARNINGS_URL: ${{ vars.REACT_APP_SHEETDB_EARNINGS_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create .env file from GitHub Actions variables
        run: |
          echo "REACT_APP_SHEETDB_CASH_URL=${REACT_APP_SHEETDB_CASH_URL}" >> .env
          echo "REACT_APP_SHEETDB_EARNINGS_URL=${REACT_APP_SHEETDB_EARNINGS_URL}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
